language: generic
sudo: required
branches:
  except:
    - /^v[0-9]*/
before_script:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
script:
- export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
- armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.chernarus.pbo
- git tag $VERSION
deploy:
  if:
    branch: master
  provider: releases
  skip_cleanup: true
  file: '7Cav_FullSpectrum_$VERSION.chernarus.pbo'
  on:
    branch: master
    repo: 7Cav/7Cav_FullSpectrum_V4.chernarus
  name: '7th Cavalry Full Spectrum $VERSION - chernarus'
  api_key:
    secure: rQuRSj5oY9ndjhz86ExH/ZOb625hZTevmvIvOlyaS7ULo/xXapHNutKLHLGmfRqWALoJgZT9BSXWxPRazky0iinA/t8iUqdjShLv5OlH/hk3iCF+RNiH22uVVnu684EwqU+ZAQYZoSKQNj/aJbm4zslGQ5vHQW5B+Vta0xRZVq7QIey3b7KoFHBXPCkA6SUy5a1u3oEjO5knstk/ZygxcSOwgwUWjeMa5wWJgoU/6gg6wnZUpC//+gDrxbTUKQHfMbWcAYZB/D1JTwQ4qaX2+mY863Vo9g46D/vKpE7oKB8q28YHKnybJEJtrkxE1olvznnW718PFU4JnBXTdRegEpYo0gceAhcJFiX/QcT65zPM1fcBXnm87W9UUpiaoH7BR/cAWnW77slwHnP8efQiio2FjzjkO8bgpZC62eKUjPRbCwDx9S9IjkNkwBD+ICG5JPJZG6iF9NzaPKZMn1wrcaMhpMv6nJT3VPKnEMxGwtQGaJ+Tsqp5fdEzSTGBq5dl0HfE4vdKBlGdUdSDELnIlyhRcPKuIQ+ZEx02S4utsko0ZcN1K50hVAp66+KoCGWok96XtEva5IMOkYPL+7ejlPPG1NKf6NxazXamaUt42qRervN2yHVfoCA8i3dLhmt0sqcKkKGDn25L/ibbkAc6/Jy0ASGtesr7NJin1ORqAWg=
